
//Get all products without productDescription
GET http://localhost:3000/products HTTP/1.1

###

//Get specific product
GET http://localhost:3000/products/1 HTTP/1.1

###

//Get all categories
GET http://localhost:3000/categories HTTP/1.1

###

//Get all products associated with specific categoryID
GET http://localhost:3000/categories/1 HTTP/1.1

###

//Create new customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerName": "Test3", "password": "12345" }

###

//Get all products in a customer's basket
GET http://localhost:3000/baskets/1 HTTP/1.1

###

//Add product to basket
PUT http://localhost:3000/baskets/1/1 HTTP/1.1

###

//Delete product from basket
DELETE http://localhost:3000/baskets/5/1 HTTP/1.1

