
//get products without productDescription
GET http://localhost:3000/products HTTP/1.1

###

//get specific produxt
GET http://localhost:3000/products/1 HTTP/1.1

###

//get all categories
GET http://localhost:3000/categories HTTP/1.1

###

//create new customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":1, "customerName": "Lena", "basketId": 1, "password": "12345" }

###

//get all products in a customer's basket
GET http://localhost:3000/baskets/2 HTTP/1.1

###

//add product to basket - yet to be implemented
PUT http://localhost:3000/baskets/1/1 HTTP/1.1

###

DELETE http://localhost:3000/baskets/4/1 HTTP/1.1