
//get products
GET http://localhost:3000/products HTTP/1.1

###

//get specific produxt
GET http://localhost:3000/products/1 HTTP/1.1

###

//get all categories
GET http://localhost:3000/categories HTTP/1.1

###

//add product to basket
POST http://localhost:3000/basket/ HTTP/1.1

###

//create new customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":2, "customerName": "Christian", "basketId": 2, "password": "12345" }
